name: melos-monorepo

packages:
  - packages/bookmark_manager_extension
  - packages/bookmark_manager_app

scripts:
  analyze:
    run: |
      melos exec -c 2 -- \
        dart analyze . --fatal-infos

  build-apk:
    description: Builds the APK File
    packageFilters:
      flutter: true
      dirExists: lib
      scope: bookmark_manager
    exec: flutter build apk

  build-extension:
    description: Builds the Extension Fille
    packageFilters:
      flutter: true
      scope: bookmark_manager_extension
    exec: flutter build web --web-renderer html --csp

  format:
    description: Formats the files
    exec: dart format . --line-length 100
