name: bookmark_manager
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  receive_sharing_intent: ^1.6.7
  dio: ^5.4.0
  concentric_transition: ^1.0.3
  modal_progress_hud_nsn: ^0.5.1
  animated_text_kit: ^4.2.2
  lottie: ^3.0.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
