name: bookmark_manager
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  receive_sharing_intent: ^1.6.7
  dio: ^5.4.0
  concentric_transition: ^1.0.3
  modal_progress_hud_nsn: ^0.5.1
  animated_text_kit: ^4.2.2
  lottie: ^3.0.0
  flashy_tab_bar2: ^0.0.6
  flutter_link_previewer: ^3.2.2
  link_preview_generator: ^1.2.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/launcher_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/launcher_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
